erp/urls.py
from django.urls import path
from erp.views import *


urlpatterns = [
    # Sub Modules
    path('get-sub-module-index/<str:module_pk>/<str:name>/', module_index, name="get-sub-module-index"),
    path('get-sub-module-index/<str:module_pk>/<str:name>/<pk>/', module_index, name="get-sub-module-index"),
    path('api/sub-module/<str:module_pk>/<str:name>/', APIViewERP.as_view(), name="sub-module-api"),
    path('api/sub-module/<str:module_pk>/<str:name>/<pk>/', APIViewERP.as_view(), name="sub-module-api"),
    path('api/sub-module/<str:module_pk>/<str:name>/<pk>/<pk_s>/', APIViewERP.as_view(), name="sub-module-api"),
    # Charts
    path('chart/get-charts/', get_charts, name="get-charts"),
    # Notifications
    path('close-notif/<int:pk_notif>/', close_notif, name='close-notif'),
    # Planning
    path('planning/', planning, name='planning'),
    path('planning/events/', planning_events, name='planning-events'),
    # Paramètres
    #   Données
    path('setting/data/', setting_data, name='setting-data'),
    path('setting/data/get-add-form/<str:name>/', setting_add_data_form, name="setting-get-add-form"),
    path('setting/data/get-add-form/<str:name>/<pk>/', setting_add_data_form, name="setting-get-add-form"),
    path('api/setting/data/<str:name>/', SettingDataAPI.as_view(), name='setting-api'),
    path('api/setting/data/<str:name>/<pk>/', SettingDataAPI.as_view(), name='setting-api'),
    #   Graphiques
    path('setting/graph/', setting_graph, name="setting-graph"),
    #   Notifications
    path('setting/notif/', setting_notif, name="setting-notif"),
]

erp/models/Notification.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class Notification(models.Model):
    WARNING = ("W", "warning")
    DANGER = ("D", "danger")
    SUCCESS = ("S", "success")
    INFO = ("I", "info")
    SEVERITY = (
        (WARNING[0], WARNING[1]),
        (DANGER[0], DANGER[1]),
        (SUCCESS[0], SUCCESS[1]),
        (INFO[0], INFO[1])
    )
    title = models.CharField(max_length=64)
    content = models.TextField(max_length=255)
    severity = models.CharField(max_length=64, choices=SEVERITY)
    closed = models.BooleanField(default=False)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.title

templates/base.html
{% load static %}

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        {% include 'snippets/css.html' %}
        {% block css %}{% endblock %}
        <title>Dashboard{% block title %}{% endblock %}</title>
    </head>

    <body>
        {% include 'snippets/nav.html' %}
        <div class="container-fluid">
            <div class="row">
                {% if user.is_authenticated %}
                    {% include 'snippets/sidebar.html' %}
                {% endif %}
                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                    {% block content %}{% endblock %}
                </main>
            </div>
        </div>
        {% if not user.is_authenticated %}
            {% include 'accounts/login_register_modal.html' %}
        {% endif %}
    </body>

    <footer>
        {% include 'snippets/script.html' %}
        {% block javascript %}{% endblock %}
    </footer>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="pt-3 pb-2 mb-3">
            <ul class="nav nav-tabs" id="module-tab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="tab-dashboard" data-toggle="tab" href="#dashboard-tab" role="tab"
                       aria-controls="dashboard" aria-selected="true">
                        Dashboard
                    </a>
                </li>
            </ul>
            <div class="tab-content" id="module-tab-content">
                <div class="tab-pane fade show active" id="dashboard-tab">
                    <div class="pt-3 pb-2 mb-3">
                        <nav class="navbar">
                            <div class="navbar-left">
                                <h4>Dashboard</h4>
                            </div>
                            <div class="navbar-right">
                                <div class="btn-group" role="group" aria-label="Tools buttons">
                                    <button type="button" class="btn btn-sm btn-outline-secondary disabled">Share
                                    </button>
                                    <button type="button" class="btn btn-sm btn-outline-secondary disabled">Export
                                    </button>
                                </div>
                                <div id="dashboard-datatable-toolbar" class="btn-group" role="group"
                                     aria-label="dashboard buttons"></div>
                            </div>
                        </nav>
                        <div class="accordion" id="dashbord-collapsible">
                            {% if notifications %}
                                <div class="card">
                                    <div class="card-header" id="notification-collapse">
                                        <h2 class="mb-0">
                                            <button class="btn btn-link" type="button" data-toggle="collapse"
                                                    data-target="#notification-content" aria-expanded="true"
                                                    aria-controls="notification-content">
                                                Notifications
                                            </button>
                                        </h2>
                                    </div>

                                    <div id="notification-content" class="collapse show"
                                         aria-labelledby="notification-content"
                                         data-parent="#dashbord-collapsible">
                                        <div class="card-body">
                                            <div class="row">
                                                {% for notification in notifications %}
                                                    <div id="notification-{{ notification.id }}"
                                                         class="col-sm-12 col-md-4">
                                                        <div class="alert alert-{{ notification.get_severity_display }}"
                                                             role="alert">
                                                            <h4 class="alert-heading">{{ notification.title }}</h4>
                                                            <p>{{ notification.content }}</p>
                                                            <hr>
                                                            <p class="mb-0">
                                                                <button id="btn-ok-notif-{{ notification.id }}"
                                                                        class="btn btn-secondary dismiss-notif">OK
                                                                </button>
                                                                <button type="button" class="btn btn-secondary"
                                                                        title="{{ notification.popover_title }}"
                                                                        data-container="body" data-toggle="popover"
                                                                        data-placement="top"
                                                                        data-content="{{ notification.popover_content }}">
                                                                    Info
                                                                </button>
                                                            </p>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                            {% for chart in charts %}
                                <div class="card">
                                    <div class="card-header" id="graph-collapse">
                                        <h2 class="mb-0">
                                            <button class="btn btn-link" type="button" data-toggle="collapse"
                                                    data-target="#graph-{{ chart.name }}" aria-expanded="true"
                                                    aria-controls="graph-content">
                                                {{ chart.name }}
                                            </button>
                                        </h2>
                                    </div>

                                    <div id="graph-{{ chart.name }}"
                                         aria-labelledby="graph-{{ chart.name }}"
                                         data-parent="#dashbord-collapsible"
                                         class="collapse
                                                {% if not notifications %}
                                                    {% if forloop.first %}
                                                        show
                                                    {% endif %}
                                                {% endif %}">
                                        <div class="card-body">
                                            <div class="row">
                                                <canvas id="chart-{{ chart.name }}"></canvas>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <script>
            onload = () => {
                $('#login-modal').modal()
            }
        </script>
    {% endif %}
{% endblock %}